# metapackage to establish priority order for tensorflow-base packages
package:
  name: _tflow_1100_select
  version: {{ tflow_variant_version }}

build:
  number: 0
  string: {{ tflow_variant_str }}
