full_base_version:
  - "1.10.0 eigen_py27h4f0eeca_0"
  - "1.10.0 eigen_py35h4f0eeca_0"
  - "1.10.0 eigen_py36h4f0eeca_0"
select_version:
  - "0.0.2 eigen"
  - "0.0.2 eigen"
  - "0.0.2 eigen"
tflow_variant:
  - "eigen"
  - "eigen"
  - "eigen"
py_version:
  - 2.7
  - 3.5
  - 3.6
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
