# configuration for win-64 gpu, cuda 9.0
full_base_version:
  - "1.10.0 gpu_py35h6e53903_0"
  - "1.10.0 gpu_py36h6e53903_0"
select_version:
  - "0.0.1 gpu"
  - "0.0.1 gpu"
tflow_variant:
  - "gpu"
  - "gpu"
py_version:
  - 3.5
  - 3.6
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
