full_base_version:              
  - "1.9.0 gpu_py27h6ecc378_0"  # [linux]
  - "1.9.0 gpu_py35h6ecc378_0"  # [linux]
  - "1.9.0 gpu_py36h6ecc378_0"  # [win]
  - "1.9.0 gpu_py35h6e53903_0"  # [win]
  - "1.9.0 gpu_py36h6e53903_0"  # [win]
select_version:                 
  - "0.0.1 gpu"   # [linux]
  - "0.0.1 gpu"
  - "0.0.1 gpu"               
tflow_variant:                  
  - "gpu"    # [linux]
  - "gpu"
  - "gpu"
py_version:                     
  - 2.7      # [linux]
  - 3.5                         
  - 3.6                         
zip_keys:                       
  - full_base_version           
  - select_version              
  - tflow_variant               
  - py_version                  
