full_base_version:
  - "1.9.0 eigen_py27hdfca3bf_0"  # [linux]
  - "1.9.0 eigen_py35hdfca3bf_0"  # [linux]
  - "1.9.0 eigen_py36hdfca3bf_0"  # [linux]
  - "1.9.0 eigen_py27h4f0eeca_0"  # [osx]
  - "1.9.0 eigen_py35h4f0eeca_0"  # [osx]
  - "1.9.0 eigen_py36h4f0eeca_0"  # [osx]
  - "1.9.0 eigen_py35h45df0d8_0"  # [win]
  - "1.9.0 eigen_py36h45df0d8_0"  # [win]
  - "1.9.0 mkl_py27h2ca6a6a_0"    # [linux]
  - "1.9.0 mkl_py35h2ca6a6a_0"    # [linux]
  - "1.9.0 mkl_py36h2ca6a6a_0"    # [linux]
  - "1.9.0 mkl_py27h70e0e9a_0"    # [osx]
  - "1.9.0 mkl_py35h70e0e9a_0"    # [osx]
  - "1.9.0 mkl_py36h70e0e9a_0"    # [osx]
select_version:
  - "0.0.2 eigen"                 # [unix]
  - "0.0.2 eigen"                 # [unix or win]
  - "0.0.2 eigen"                 # [unix or win]
  - "0.0.3 mkl"                   # [unix]
  - "0.0.3 mkl"                   # [unix]
  - "0.0.3 mkl"                   # [unix]
tflow_variant:
  - "eigen"                       # [unix]
  - "eigen"                       # [unix or win]
  - "eigen"                       # [unix or win]
  - "mkl"                         # [unix]
  - "mkl"                         # [unix]
  - "mkl"                         # [unix]
py_version:
  - 2.7                           # [unix]
  - 3.5                           # [unix or win]
  - 3.6                           # [unix or win]
  - 2.7                           # [unix]
  - 3.5                           # [unix]
  - 3.6                           # [unix]
zip_keys:
  - full_base_version
  - select_version
  - tflow_variant
  - py_version
