full_base_version:            # [linux]
  - 1.8.0=py27hee38f2d_0      # [linux]
  - 1.8.0=py35hee38f2d_0      # [linux]
  - 1.8.0=py36hee38f2d_0      # [linux]
  - 1.8.0=py27h5f64886_0      # [linux]
  - 1.8.0=py35h5f64886_0      # [linux]
  - 1.8.0=py36h5f64886_0      # [linux]
select_version:               # [linux]
  - 2.0=mkl                   # [linux]
  - 2.0=mkl                   # [linux]
  - 2.0=mkl                   # [linux]
  - 3.0=eigen                 # [linux]
  - 3.0=eigen                 # [linux]
  - 3.0=eigen                 # [linux]
zip_keys:                     # [linux]
  - full_base_version         # [linux]
  - select_version            # [linux]
